title:            Lan 的梦想小镇
description:      成长中...
disqus_shortname: hpstrtheme
reading_time:     true
words_per_minute: 100
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://www.zhouchengjian517.com

# Owner/author information
owner:
  name:           Chengjian Zhou
  avatar:         avatar.jpg
  bio:            "成功不相信眼泪只相信汗水"
  email:          494651913@qq.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:        /lanixzcj
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    

# Background image to be tiled on all pages
background: witewall_3.png


# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Beijing
future:      true
highlighter: pygments
markdown:    redcarpet
safe: true
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input:  GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: rouge
  use_coderay: use

redcarpet:
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]